### ISSUE TITLE
Development Roadmap #1

### ISSUE THREAD

**Issue by Seeloewen** [Seeloewen/Seeloewen#1]
Ever since I started programming, I've been making roadmaps on different projects. There was, however, never a general roadmap of which project I'm working on. That's what this issue is going to solve. It contains a chronological order of the projects I'm going to work on next. Nothing more, nothing less. When this roadmap is completed, there might be a new one. Please note that I will never give any ETA until I'm absolutely sure when to release it as it adds a lot of pressure. The updates are ready when I think they are the best quality that I can deliver. I might also break the chronological order if I feel like it or if it's absolutely necessary, but I'm trying to stick to it for the most part. Some of the projects listed below may also be private projects.

The following projects will be worked on in chronological order:

- [ ] Random Item Giver 1.5.0-Beta10 (for 24w13a)
- [ ]  **Random Item Giver** Settings window
- [ ]  **Seeloewen Sync** Version 0.5.0 [(Seeloewen Sync #4)](https://github.com/Seeloewen/Seeloewen-Sync/issues/4)
- [ ]  **Profile Manager Demo** Profile Renaming & Darkmode Support [(Profile Manager Demo #5)](https://github.com/Seeloewen/Profile-Manager-Demo/issues/5)
- [ ] Seeloewen Flap Version 1.1.1
- [ ] SealFisher 1.0.0
- [ ] SeeloewenCraft 1.1.1
- [ ] Random Item Giver 1.4.5
- [ ] Seeloewen AntiCrash partial rework part 1

**Comment by Seeloewen** [comment]
This will no longer be worked on. I will finish the points on the list and that's it
